# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/actionpack/all/actionpack.rbi
#
# actionpack-7.1.3.4

module ActionController
end
class ActionController::Metal < AbstractController::Base
  include ActionController::Testing::Functional
end
module ActionController::Live
end
class ActionController::TestRequest < ActionDispatch::TestRequest
end
class ActionController::LiveTestResponse < ActionController::Live::Response
end
class ActionController::TestSession < Rack::Session::Abstract::PersistedSecure::SecureSessionHash
end
class ActionController::TestCase < ActiveSupport::TestCase
  extend ActionController::TestCase::Behavior::ClassMethods
  extend ActionDispatch::Assertions::RoutingAssertions::ClassMethods
  extend ActiveSupport::Testing::ConstantLookup::ClassMethods
  include ActionController::TemplateAssertions
  include ActionController::TestCase::Behavior
  include ActionDispatch::Assertions
  include ActionDispatch::Assertions::RoutingAssertions
  include ActiveSupport::Testing::ConstantLookup
end
module ActionController::TestCase::Behavior
  extend ActiveSupport::Concern
  include ActionDispatch::TestProcess
  include ActiveSupport::Testing::ConstantLookup
  include Rails::Dom::Testing::Assertions
end
module ActionController::TestCase::Behavior::ClassMethods
end
