# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/activesupport/all/activesupport.rbi
#
# activesupport-7.1.3.4

module ActiveSupport
end
class ActiveSupport::TestCase < Minitest::Test
  extend ActiveSupport::Callbacks::ClassMethods
  extend ActiveSupport::DescendantsTracker
  extend ActiveSupport::Testing::Declarative
  extend ActiveSupport::Testing::SetupAndTeardown::ClassMethods
  include ActionCable::TestHelper
  include ActiveSupport::Callbacks
  include ActiveSupport::Executor::TestHelper
  include ActiveSupport::Testing::Assertions
  include ActiveSupport::Testing::ConstantStubbing
  include ActiveSupport::Testing::Deprecation
  include ActiveSupport::Testing::ErrorReporterAssertions
  include ActiveSupport::Testing::FileFixtures
  include ActiveSupport::Testing::TaggedLogging
  include ActiveSupport::Testing::TimeHelpers
  include Turbo::Broadcastable::TestHelper
  include Turbo::Streams::StreamName
  include Turbo::TestAssertions
end
