# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/activerecord/all/activerecord.rbi
#
# activerecord-7.1.3.4

module ActiveRecord
end
class ActiveRecord::Schema < ActiveRecord::Migration::Current
  extend ActiveRecord::Schema::Definition::ClassMethods
  include ActiveRecord::Schema::Definition
end
module ActiveRecord::Schema::Definition
  extend ActiveSupport::Concern
end
module ActiveRecord::Schema::Definition::ClassMethods
end
