# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/date/all/date.rbi
#
# date-3.3.4

class Date
  def infinite?; end
end
class Date::Infinity < Numeric
  def +@; end
  def -@; end
  def <=>(other); end
  def abs; end
  def coerce(other); end
  def d; end
  def finite?; end
  def infinite?; end
  def initialize(d = nil); end
  def nan?; end
  def to_f; end
  def zero?; end
end
