# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/pg/all/pg.rbi
#
# pg-1.5.6

module PG
  def self.connect(*args, &block); end
  def self.make_shareable(obj); end
  def self.version_string(include_buildnum = nil); end
end
module PG::BinaryDecoder
end
module PG::BinaryEncoder
end
module PG::TextDecoder
end
module PG::TextEncoder
end
