# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/rack/all/rack.rbi
#
# rack-3.1.3

module Rack
end
class Rack::Files
end
class Rack::Files::BaseIterator
end
class Rack::Files::Iterator < Rack::Files::BaseIterator
end
