# typed: strict

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `ruby2_keywords` gem.
# Please instead update this file by running `bin/tapioca gem ruby2_keywords`.


# source://ruby2_keywords//lib/ruby2_keywords.rb#1
class Module
  include ::Module::Concerning
end

class Module::DelegationError < ::NoMethodError; end
