# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/web-console/all/web-console.rbi
#
# web-console-4.2.1

module WebConsole
end
class WebConsole::Request < ActionDispatch::Request
end
class WebConsole::Request::GetSecureIp < ActionDispatch::RemoteIp::GetIp
end
