AllCops:
  Exclude:
    - db/migrate/**/*
    - db/schema.rb
    - config/**/*
    - script/**/*
    - bin/**/*
    - app/admin/**/*
    - app/channels/**/*
    - app/jobs/**/*
    - node_modules/**/*
    - Rakefile
    - config.ru
require:
  - rubocop-rails
  - rubocop-sorbet
  - ./lib/rubocop/init_autoloader

Custom/PrivateMethodStyle:
  Enabled: true
Layout/IndentationWidth:
  Enabled: true
  Width: 2
Lint/UnusedMethodArgument:
  AutoCorrect: false
Sorbet/EnforceSigilOrder:
  Enabled: false
Style/AccessModifierDeclarations:
  EnforcedStyle: inline
Style/Documentation:
  Enabled: false
Style/Lambda:
  EnforcedStyle: literal
Style/RedundantArgument:
  AutoCorrect: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
