# DO NOT EDIT MANUALLY
# This is an autogenerated file for unresolved constants.
# Please instead update this file by running `bin/tapioca todo`.

# typed: false

module ::Anonymous_Delegator_20; end
module ::Anonymous_Delegator_6; end
module ActionMailer::Base::HelperMethods::Anonymous_Module_25; end
module ActionView::TestCase::TestController::Anonymous_Module_38; end
